In [39]:
import pandas as pd
df=pd.read_csv("modis_ndvi_series (1).csv",sep=";")
df=df.set_index("id")

In [40]:
df.columns=pd.to_datetime(df.columns, format='%Y_%m_%d')

In [6]:
df.to_csv("data.csv")

In [48]:
df

,2015-01-01,2015-01-17,2015-02-02,2015-02-18,2015-03-06,2015-03-22,2015-04-07,2015-04-23,2015-05-09,2015-05-25,...,2024-04-06,2024-04-22,2024-05-08,2024-05-24,2024-06-09,2024-06-25,2024-07-11,2024-07-27,2024-08-12,2024-08-28
id,,,,,,,,,,,,,,,,,,,,,
1,0.44,0.44,0.40,0.35,0.35,0.31,0.29,0.33,0.37,0.38,...,0.37,0.34,0.39,0.40,0.33,0.41,0.44,0.48,0.51,0.59
2,0.19,0.20,0.22,0.21,0.19,0.19,0.18,0.18,0.18,0.19,...,0.19,0.20,0.20,0.20,0.18,0.19,0.20,0.21,0.23,0.17
3,0.17,0.18,0.19,0.18,0.17,0.17,0.17,0.17,0.17,0.18,...,0.19,0.19,0.19,0.19,0.17,0.18,0.19,0.21,0.23,0.23
4,0.16,0.18,0.18,0.18,0.17,0.17,0.17,0.16,0.16,0.17,...,0.17,0.18,0.18,0.17,0.16,0.17,0.18,0.19,0.19,0.18
5,0.19,0.22,0.21,0.19,0.18,0.19,0.18,0.18,0.18,0.19,...,0.18,0.19,0.19,0.18,0.17,0.18,0.19,0.19,0.22,0.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,0.27,0.26,0.26,0.24,0.21,0.24,0.23,0.23,0.23,0.23,...,0.23,0.22,0.23,0.25,0.21,0.24,0.30,0.43,0.64,0.70
190,0.27,0.25,0.25,0.24,0.21,0.25,0.24,0.24,0.23,0.23,...,0.25,0.24,0.25,0.27,0.25,0.25,0.43,0.55,0.64,0.68
191,0.28,0.25,0.27,0.25,0.23,0.27,0.26,0.26,0.26,0.30,...,0.29,0.28,0.28,0.35,0.41,0.53,0.63,0.50,0.68,0.67
192,0.23,0.22,0.22,0.20,0.18,0.19,0.18,0.17,0.17,0.17,...,0.20,0.20,0.19,0.20,0.19,0.20,0.22,0.35,0.41,0.52
193,0.08,0.10,0.15,0.13,0.09,0.08,0.10,0.09,0.06,0.08,...,0.08,0.09,0.10,0.12,0.11,0.14,0.14,0.17,0.21,0.15

86078